name: Build and deploy prod

on:
  push:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checout repo
        uses: actions/checkout@main
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test
  build:
    name: Build
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checout repo
        uses: actions/checkout@main
      - name: Install dependencies
        run: npm ci
      - name: Build dependecies
        run: npm run build
      - name: Archive production artifact
        uses: actions/upload-artifact@main
        with:
          name: build
          path: build
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@main
      - name: Download artifact
        uses: actions/download-artifact@main
        with:
          name: build
          path: build
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
